# fly.toml app configuration file generated for simulatorebolette on 2026-07-24T11:28:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'simulatorebolette'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[env]
  DB_POOL_SIZE = '5'
  DDL_AUTO = 'validate'
  FLYWAY_ENABLED = 'true'
  JAVA_OPTS = '-XX:MaxRAMPercentage=70 -XX:+UseSerialGC -XX:TieredStopAtLevel=1 -Xss512k'
  LOG_LEVEL = 'INFO'
  PORT = '8080'
  SHOW_SQL = 'false'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 60
    soft_limit = 40

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '1m30s'
    method = 'GET'
    path = '/actuator/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
