-- ════════════════════════════════════════════════════════════════════════════
-- Conformita ARERA: flag normativi, valori annui, scaglioni di consumo.
-- V1 e' gia' applicata in produzione: le colonne rimosse dalle entity restano nel DB
-- (Hibernate validate ignora le colonne in eccesso) e qui si aggiungono le nuove.
-- ════════════════════════════════════════════════════════════════════════════

-- ── parametri_gestore: flag di conformita ────────────────────────────────────
ALTER TABLE parametri_gestore ADD COLUMN applica_esenzione_accisa_residenti BOOLEAN;
ALTER TABLE parametri_gestore ADD COLUMN applica_scaglioni                  BOOLEAN;
ALTER TABLE parametri_gestore ADD COLUMN quota_fissa_solo_non_residenti     BOOLEAN;
ALTER TABLE parametri_gestore ADD COLUMN supporta_aliquote_miste            BOOLEAN;
ALTER TABLE parametri_gestore ADD COLUMN riferimento_delibera               VARCHAR(255);

-- ── parametri_gestore: trasporto/oneri su base annua ─────────────────────────
ALTER TABLE parametri_gestore ADD COLUMN trasporto_quota_fissa_annua    NUMERIC(14, 8);
ALTER TABLE parametri_gestore ADD COLUMN trasporto_quota_potenza_annua  NUMERIC(14, 8);
ALTER TABLE parametri_gestore ADD COLUMN quota_potenza_solo_non_domestici BOOLEAN;
ALTER TABLE parametri_gestore ADD COLUMN asos_quota_fissa_annua         NUMERIC(14, 8);
ALTER TABLE parametri_gestore ADD COLUMN arim_quota_fissa_annua         NUMERIC(14, 8);

-- ── parametri_gestore: soglie accisa ─────────────────────────────────────────
ALTER TABLE parametri_gestore ADD COLUMN soglia_esenzione_kwh_mese   NUMERIC(12, 2);
ALTER TABLE parametri_gestore ADD COLUMN potenza_max_esenzione_kw    NUMERIC(12, 2);
ALTER TABLE parametri_gestore ADD COLUMN soglia_erosione_kwh_mese1_5 NUMERIC(12, 2);
ALTER TABLE parametri_gestore ADD COLUMN soglia_erosione_kwh_mese3   NUMERIC(12, 2);

-- ── bollette_concorrenti: consumo annuo noto (per la stima del risparmio) ────
ALTER TABLE bollette_concorrenti ADD COLUMN consumo_annuo_kwh NUMERIC(12, 2);

-- ── mesi_bolletta: giorni del periodo ────────────────────────────────────────
ALTER TABLE mesi_bolletta ADD COLUMN giorni_periodo INTEGER;

-- ── altre_partite: onere amministrativo ──────────────────────────────────────
ALTER TABLE altre_partite ADD COLUMN onere_amministrativo BOOLEAN;

-- ── voci_corrispettivo: riferimento normativo ────────────────────────────────
ALTER TABLE voci_corrispettivo ADD COLUMN riferimento_normativo VARCHAR(255);

-- ── scaglioni_consumo: nuova tabella ─────────────────────────────────────────
CREATE TABLE scaglioni_consumo (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parametri_id     BIGINT,
    componente       VARCHAR(255)   NOT NULL,
    tipo_cliente     VARCHAR(255),
    limite_inferiore NUMERIC(12, 2) NOT NULL,
    limite_superiore NUMERIC(12, 2),
    valore           NUMERIC(14, 8) NOT NULL,
    unita_misura     VARCHAR(255),
    ordine           INTEGER,
    CONSTRAINT fk_scaglione_parametri FOREIGN KEY (parametri_id) REFERENCES parametri_gestore (id)
);
